# Generated by Django 2.2.3 on 2019-09-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chest_pain',
            name='associated_symptoms',
            field=models.CharField(choices=[('chills', 'Chills'), ('cough', 'Cough'), ('diaphoresis', 'Diaphoresis'), ('difficulty_swallowing', 'Difficulty Swallowing'), ('fever', 'Fever'), ('focal_neurologic_sign', 'Focal Neurologic Sign'), ('hematochezia', 'Hematochezia'), ('immobilization', 'Immobilization (>= 3 days) or surgery in the previous four weeks'), ('leg_swelling', 'Leg Swelling'), ('nausea', 'Nausea'), ('numbness', 'Numbness'), ('hemoptysis', 'Presence of Hemoptysis'), ('rash', 'Rash'), ('trauma_exertion', 'Recent Trauma or Physical Exertion'), ('severe_angina', 'Severe angina (≥2 episodes in 24 hrs)'), ('shortness_breath', 'Shortness of Breath'), ('syncope', 'Syncope'), ('tingling', 'Tingling'), ('vomiting', 'Vomiting'), ('vomiting_blood', 'Vomiting Blood'), ('weakness', 'Weakness')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='improves_with',
            field=models.CharField(choices=[('burping', 'Burping'), ('eating', 'Eating'), ('exertion', 'Exertion'), ('lying_down', 'Lying Down'), ('nitro', 'Nitro'), ('palpation', 'Palpation'), ('resting', 'Resting'), ('sitting_up', 'Sitting up'), ('spicy_food', 'Spicy Food'), ('taking_breath', 'Taking a deep breath'), ('walking', 'Walking')], max_length=2000),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='intensity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=200),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='worsens_with',
            field=models.CharField(choices=[('burping', 'Burping'), ('eating', 'Eating'), ('exertion', 'Exertion'), ('lying_down', 'Lying Down'), ('nitro', 'Nitro'), ('palpation', 'Palpation'), ('resting', 'Resting'), ('sitting_up', 'Sitting up'), ('spicy_food', 'Spicy Food'), ('taking_breath', 'Taking a deep breath'), ('walking', 'Walking')], max_length=2000),
        ),
    ]
