# Generated by Django 2.2.3 on 2019-09-01 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_auto_20190901_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chest_pain',
            name='vitals',
        ),
    ]
