# Generated by Django 2.2.3 on 2019-09-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_remove_chest_pain_vitals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chest_pain',
            name='race',
            field=models.CharField(choices=[('white', 'White'), ('black', 'Black or African American'), ('american_indian', 'American Indian or Alaska Native'), ('asian', 'Asian'), ('native_hawaiian', 'Native Hawaiian or Other Pacific Islander'), ('some_other', 'Some Other Race')], max_length=100),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='sex',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=100),
        ),
    ]
