# Generated by Django 2.2.3 on 2019-09-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0004_auto_20190906_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chest_pain',
            name='diastolic_blood_pressure',
            field=models.CharField(choices=[('41-60', '41-60'), ('61-80', '61-80'), ('81-90', '81-90'), ('91-100', '91-100')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='pulse',
            field=models.CharField(choices=[('61-100', '61-100'), ('101-120', '101-120'), ('121-150', '121-150')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='pulse_oximetry',
            field=models.CharField(choices=[('90-94', '90-94'), ('94-100', '94-100')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='systolic_blood_pressure',
            field=models.CharField(choices=[('60-89', '60-89'), ('90-120', '90-120'), ('121-139', '121-139'), ('140-179', '140-179'), ('180-220', '180-220')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='temperature',
            field=models.CharField(choices=[('<=95(35)', '<=95(35)'), ('95.1-97.7(35.1-36.5)', '95.1 - 97.7 (35.1 - 36.5)'), ('97.8-99.4(36.5-37.4)', '97.8 -99.4 (36.5-37.4)'), ('99.5-100.3(37.6-37.9)', '99.5 - 100.3 (37.6 - 37.9)'), ('100.5-101.9(38.0-38.9)', '100.5 - 101.9 (38.0 - 38.9)'), ('>=102(>=38.9)', '>=102 (>=38.9)')], max_length=1000),
        ),
    ]
