# Generated by Django 2.2.3 on 2019-09-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0005_auto_20190906_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chest_pain',
            name='associated_symptoms',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='diastolic_blood_pressure',
            field=models.CharField(choices=[('<41', '<41'), ('41-60', '41-60'), ('61-80', '61-80'), ('81-90', '81-90'), ('91-100', '91-100'), ('>100', '>100')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='family_and_social_hx',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='medication',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='past_medical_history_of',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='physical_exam',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='pulse',
            field=models.CharField(choices=[('<60', '<60'), ('61-100', '61-100'), ('101-120', '101-120'), ('121-150', '121-150'), ('>150', '>150')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='pulse_oximetry',
            field=models.CharField(choices=[('<90', '<90'), ('90-94', '90-94'), ('94-100', '94-100')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='quality',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='similar_to_prior',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='systolic_blood_pressure',
            field=models.CharField(choices=[('<60', '<60'), ('60-89', '60-89'), ('90-120', '90-120'), ('121-139', '121-139'), ('140-179', '140-179'), ('180-220', '180-220'), ('>220', '>220')], max_length=1000),
        ),
    ]
