# Generated by Django 2.2.3 on 2019-09-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0007_auto_20190906_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chest_pain',
            name='associated_symptoms',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='diastolic_blood_pressure',
            field=models.CharField(blank=True, choices=[('<41', '<41'), ('41-60', '41-60'), ('61-80', '61-80'), ('81-90', '81-90'), ('91-100', '91-100'), ('>100', '>100')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='family_and_social_hx',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='improves_with',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='intensity',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='medication',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='past_medical_history_of',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='physical_exam',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='pulse',
            field=models.CharField(blank=True, choices=[('<60', '<60'), ('61-100', '61-100'), ('101-120', '101-120'), ('121-150', '121-150'), ('>150', '>150')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='pulse_oximetry',
            field=models.CharField(blank=True, choices=[('<90', '<90'), ('90-94', '90-94'), ('94-100', '94-100')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='quality',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='race',
            field=models.CharField(blank=True, choices=[('white', 'White'), ('black', 'Black or African American'), ('american_indian', 'American Indian or Alaska Native'), ('asian', 'Asian'), ('native_hawaiian', 'Native Hawaiian or Other Pacific Islander'), ('some_other', 'Some Other Race')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='similar_to_prior',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='systolic_blood_pressure',
            field=models.CharField(blank=True, choices=[('<60', '<60'), ('60-89', '60-89'), ('90-120', '90-120'), ('121-139', '121-139'), ('140-179', '140-179'), ('180-220', '180-220'), ('>220', '>220')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='temperature',
            field=models.CharField(blank=True, choices=[('<=95(35)', '<=95(35)'), ('95.1-97.7(35.1-36.5)', '95.1 - 97.7 (35.1 - 36.5)'), ('97.8-99.4(36.5-37.4)', '97.8 -99.4 (36.5-37.4)'), ('99.5-100.3(37.6-37.9)', '99.5 - 100.3 (37.6 - 37.9)'), ('100.5-101.9(38.0-38.9)', '100.5 - 101.9 (38.0 - 38.9)'), ('>=102(>=38.9)', '>=102 (>=38.9)')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='worsens_with',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
