# Generated by Django 2.2.3 on 2019-09-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0008_auto_20190906_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chest_pain',
            name='sex',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=100, null=True),
        ),
    ]
