# Generated by Django 2.2.3 on 2019-09-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0009_auto_20190912_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chest_pain',
            name='intensity',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='race',
            field=models.CharField(blank=True, choices=[('White', 'White'), ('Black or African American', 'Black or African American'), ('American Indian or Alaska Native', 'American Indian or Alaska Native'), ('Asian', 'Asian'), ('Native Hawaiian or Other Pacific Islander', 'Native Hawaiian or Other Pacific Islander'), ('Some Other Race', 'Some Other Race')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chest_pain',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True),
        ),
    ]
