# Generated by Django 2.2.3 on 2019-09-16 06:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0011_auto_20190916_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='chest_pain',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
