# Generated by Django 2.2.3 on 2019-09-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0012_chest_pain_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='chest_pain',
            name='more',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
